name: Go Build & Test
on: 
  push:
    paths:
      - '**.go'
      - '**.yaml'
      - '**.yml'      
    branches:
      - '*'
    tags-ignore:
      - '*'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        path: go/src/github.com/cybertec-postgresql/pg_timetable
        fetch-depth: 1

    - name: Get dependencies
      run: |
        export GOPATH=/home/runner/work/pg_timetable/go
        go get -v -t -d ./...
        echo
        echo "-- Environment variables ----------------------------------------------"
        env
        echo "-----------------------------------------------------------------------"

    - name: Build
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.24.0
        ./bin/golangci-lint run -v

    - name: Vet
      run: |
        export GOPATH=/home/runner/work/pg_timetable/go
        go vet ./...

    - name: Lint
      run: |
        export GOPATH=/home/runner/work/pg_timetable/go
        GOBIN=$PWD/bin go get -u golang.org/x/lint/golint
        ./bin/golint ./...
